version: '3.8'

services:
  nodejs-app:
    build: ./nodejs-app
    container_name: nodejs-app
    image: node:14
    command: node /app/server.js
    volumes:
      - ./nodejs-app:/app
    ports:
      - "3000:3000"

  python-app:
    build:
      context: ./python-app
      dockerfile: Dockerfile
    container_name: python-app
    ports:
      - "8000:8000"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/letsencrypt/live
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - nodejs-app
      - python-app
   
