Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.network "public_network", bridge: "enp2s0", ip: "192.168.0.169"
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "forwarded_port", guest: 443, host: 8443
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.cpus = 2
  end

  config.vm.synced_folder "./data", "/var/www/html"

  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update
    sudo apt-get install -y docker.io docker-compose
    sudo usermod -aG docker vagrant
    sudo mkdir -p "/etc/nginx/"
    sudo mkdir -p "/etc/letsencrypt/live/misterigriks.com"
    scp /vagrant/sert/fullchain.pem /etc/letsencrypt/live/misterigriks.com/fullchain.pem
    scp /vagrant/sert/privkey.pem /etc/letsencrypt/live/misterigriks.com/privkey.pem
    sudo docker-compose -f /vagrant/docker-compose.yml up -d
  SHELL
end

