version: '3.8'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql

  drupal:
    image: drupal:9
    restart: always
    depends_on:
      - db
    environment:
      DRUPAL_DATABASE_HOST: db
      DRUPAL_DATABASE_PORT: 3306
      DRUPAL_DATABASE_NAME: drupal
      DRUPAL_DATABASE_USER: drupal
      DRUPAL_DATABASE_PASSWORD: drupal
    ports:
      - "8080:80"
    volumes:
      - drupal_data:/var/www/html

volumes:
  db_data:
  drupal_data:

